name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Backend
        working-directory: ./backend
        run: pm2 restart all || pm2 start server.js

      - name: Check PM2 Status
        run: pm2 status